[common]
language = "lean"
executable = "lean"

[sonnet]
max_iterations = 5
model_name = "claude-3-5-sonnet-20241022"
max_tokens_per_completion = 8000 # api limit is here

[o1]
max_iterations = 5
model_name = "claude-3-5-sonnet-20240620"
max_tokens_per_completion = 8000

[gemini]
max_iterations = 5
model_name = "gemini-1.5-pro"
max_tokens_per_completion = 8000

[prover_rl]
max_iterations = 100
model_name = "deepseek-ai/DeepSeek-Prover-V1.5-RL"
max_tokens_per_completion = 8000

[llama]
max_iterations = 5
model_name = "meta-llama/Llama-3.2-3B-Instruct"
max_tokens_per_completion = 8000

[testhf]
max_iterations = 5
model_name = "HuggingFaceTB/SmolLM-135M-Instruct"
max_tokens_per_completion = 200
