[common]
max_iterations = 5
language = "lean"
executable = "lean"

[sonnet]
model_name = "claude-3-5-sonnet-20240620"
max_tokens_per_completion = 8000 # api limit is here

[o1]
model_name = "claude-3-5-sonnet-20240620"
max_tokens_per_completion = 8000

[prover_rl]
model_name = "deepseek-ai/DeepSeek-Prover-V1.5-RL"
max_tokens_per_completion = 8000

[llama]
model_name = "meta-llama/Llama-3.2-3B-Instruct"
max_tokens_per_completion = 8000

[testhf]
model_name = "HuggingFaceTB/SmolLM-135M-Instruct"
max_tokens_per_completion = 200
