[lean_agent_sonnet35_baseline]
model_name = "claude-3-5-sonnet-20240620"
max_tokens_per_completion = 1024
max_iterations = 5
language = "lean"
executable = "lean"

[lean_agent_4o_mini_baseline]
model_name = "gpt-4o-mini"
max_tokens_per_completion = 1024
max_iterations = 5
language = "lean"
executable = "lean"
