[python]
model_name = "claude-3-5-sonnet-20240620"
max_tokens_per_completion = 1024
max_iterations = 4
language = "python"

[lean]
model_name = "claude-3-5-sonnet-20240620"
max_tokens_per_completion = 1024
max_iterations = 4
language = "lean"
